[New] Wrote document for icons
ised-ocp-dev/wet-react pull request #22
Opened 2022-05-18 21:19 UTC by P4ul1029

⭐ **New Features:**
Imported Font Awesome and various Font Awesome icon packages. Created a story detailing how to use Font Awesome icons.

ℹ️ **Related Issues:**
#21 

📷 **Screenshots:** _(if applicable)_

2022-06-06 19:13 UTC, Rizvida1 requested changes

2022-06-06 19:13 UTC, Rizvida1 commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.1.18",
I think we need to add these to devDependencies instead

2022-06-06 20:24 UTC, P4ul1029 commented
@Rizvida1 I merged the changes I made (moving the package names to devDependencies) to other branches. All the tests passed this PR, but on my Carousel component PR the test failed because of this error:
![image](https://user-images.githubusercontent.com/46769064/172242306-2a6b05ca-ab31-4194-84ab-58e65bd7688d.png)
Should I move those package names back to dependencies?

2022-06-09 20:38 UTC, P4ul1029 commented
> @Rizvida1 I merged the changes I made (moving the package names to devDependencies) to other branches. All the tests passed this PR, but on my Carousel component PR the test failed because of this error: ![image](https://user-images.githubusercontent.com/46769064/172242306-2a6b05ca-ab31-4194-84ab-58e65bd7688d.png) Should I move those package names back to dependencies?

I moved them back for the time being to resolve errors on my other branches.

2022-06-16 03:00 UTC, Rizvida1 approved these changes

2022-06-16 14:55 UTC, merged