[New] Added Archived Component
ised-ocp-dev/wet-react pull request #34
Opened 2022-05-31 14:37 UTC by YaBoiBreezy

⭐ **New Features:**

- description of feature 1
- description of feature 2

ℹ️ **Related Issues:**

resolves _[add ticket reference]_

📷 **Screenshots:** _(if applicable)_

2022-06-08 17:11 UTC, Rizvida1 requested changes

2022-06-08 17:11 UTC, Rizvida1 commented on src/components/Archived/Archived.css
> +*/
Please delete unnecessary files

2022-06-08 17:56 UTC, YaBoiBreezy commented on src/components/Archived/Archived.css
> +*/
Improved and deleted

2022-06-17 03:48 UTC, Rizvida1 approved these changes

2022-06-17 11:40 UTC, merged