[New] Media Player Component
ised-ocp-dev/wet-react pull request #56
Opened 2022-06-15 19:08 UTC by YaBoiBreezy

⭐ **New Features:**

- description of feature 1
- description of feature 2

ℹ️ **Related Issues:**

resolves #55 

📷 **Screenshots:** _(if applicable)_

2022-06-16 03:09 UTC, Rizvida1 requested changes

2022-06-16 03:09 UTC, Rizvida1 commented on src/components/MultimediaPlayer/stories/MultimediaPlayer.figCaption.stories.mdx
> +Add a `figcaption` with the title of the video or audio file. If a transcript is required, then also include either a link to
Make sure the capitalization is correct

2022-06-16 18:44 UTC, YaBoiBreezy commented
Need shareWidget to finish this, so can't merge until shareWidget is merged

2022-06-17 04:16 UTC, Rizvida1 approved these changes

2022-06-20 17:30 UTC, Rizvida1 approved these changes

2022-06-20 17:31 UTC, merged